---

- name: Create Azure storage account
  azure_rm_storageaccount:
    resource_group: '{{ az_resource_group }}'
    name: '{{ az_stg_account }}'
    type: Standard_LRS
    state: present

- name: Get sas token through oauth2
  uri:
    url: "https://login.windows.net/{{ lookup('env', 'ARM_TENANT_ID') }}/oauth2/token"
    method: POST
    body: "resource=https://management.core.windows.net&client_id={{ lookup('env', 'ARM_CLIENT_ID') }}&grant_type=client_credentials&client_secret={{ lookup('env', 'ARM_CLIENT_SECRET') }}"
    return_content: yes
  register: sas_token_info

- name: get the storage account keys
  uri:
    url: "https://management.azure.com/subscriptions/{{ lookup('env', 'ARM_SUBSCRIPTION_ID') }}/resourceGroups/{{ az_resource_group }}/providers/Microsoft.Storage/storageAccounts/{{ az_stg_account }}/listKeys?api-version=2016-12-01"
    method: POST
    headers:
      Authorization: "Bearer {{ sas_token_info.json.access_token }}"
      Content-Length: 0
    return_content: yes
  register: storage_account_keys  

- name: Create storage account container
  azure_rm_storageblob:
    resource_group: '{{ az_resource_group }}'
    storage_account_name: '{{ az_stg_account }}'
    container: '{{ az_stg_account }}-{{ raf_cdap_cluster_name }}'
    public_access: container
    state: present

- name: Create Azure subnet
  azure_rm_subnet:
    name: '{{ az_resource_group }}-{{ raf_cdap_cluster_name }}' 
    virtual_network_name: '{{ az_resource_group }}'
    resource_group: '{{ az_resource_group }}'
    address_prefix_cidr: "{{ raf_cdap_subnet_cidr }}"
    security_group: '{{ az_resource_group }}-default'
    state: present

- name: Create Reflex HDInsight cluster with CDAP
  azure_rm_deployment:
    state: present
    template_link: 'https://ankurhdistg.blob.core.windows.net/reflex/azuredeploy.json'
    resource_group_name: '{{ az_resource_group }}'
    location: '{{ az_location }}'
    parameters:
      clusterName:
        value: '{{ raf_cdap_cluster_name }}'
      clusterLoginPassword:
        value: '{{ raf_cdap_cluster_login_password }}'
      sshUserName:
        value: '{{ raf_cdap_cluster_ssh_user }}'
      sshPassword:
        value: '{{ raf_cdap_cluster_login_password }}'
      defaultStorageAccountName:
        value: '{{ az_stg_account }}'
      defaultStorageAccountKey:
        value: "{{ storage_account_keys.json['keys'].0.value }}"
      defaultContainerName:
        value: '{{ az_stg_account }}-{{ raf_cdap_cluster_name }}'
      workerNodeSize:
        value: '{{ raf_worker_node_size }}'
      workerCount:
        value: '{{ raf_worker_node_count }}'
      vnetName:
        value: '{{ az_resource_group }}'
      subnetName:
        value: '{{ az_resource_group }}-{{ raf_cdap_cluster_name }}'
