---

- name: Get zk hosts list
  shell: "cat /etc/hbase/conf/hbase-site.xml  | grep -A 1 hbase.zookeeper.quorum | grep value | sed 's/^.*<value>//;s/<\\/value>.*$//' | tr ',' '\n'"
  register: zk_host_list
  when: groups['zookeeper-nodes'] | length == 0

- name: Add hosts to zookeeper-nodes group
  add_host:
    hostname: "{{ item }}"
    groups: zookeeper-nodes
  with_items:
    - '{{ zk_host_list.stdout_lines }}'

- name: Create cdap group
  group:
    name: cdap
    gid: 504
    state: present

- name: Create cdap user
  user:
    name: cdap
    uid: 503
    state: present
    group: cdap

- name: Create hdfs directories & set permissions
  shell: "hdfs dfs -mkdir -p {{ item.path }} && hdfs dfs -chown {{ item.user }}:{{ item.group }} {{ item.path }} && touch /tmp/{{ item.path | regex_replace('/','_') }}"
  args:
    creates: "/tmp/{{ item.path | regex_replace('/','_') }}"
  with_items:
    - { path: '/user/yarn', user: 'yarn', group: 'yarn' }
    - { path: '/user/cdap', user: 'cdap', group: 'cdap' }
    - { path: '/cdap', user: 'yarn', group: 'hdfs' }
    - { path: '/cdap/tx.snapshot', user: 'yarn', group: 'hdfs' }

- name: Create local directories
  file:
    path: '{{ item.path }}'
    owner: '{{ item.user }}'
    group: '{{ item.group }}'
    state: directory
  with_items:
    - { path: '/var/log/cdap', user: 'cdap', group: 'cdap' }
    - { path: '/var/cdap/kafka-logs', user: 'cdap', group: 'cdap' }
    - { path: '/var/cdap/run', user: 'cdap', group: 'cdap' }

- name: Check if cdap is installed
  command: dpkg-query -l cdap
  register: cdap_check
  ignore_errors: yes

- name: Remove pre-existing '/cdap' znode from zookeeper
  znode:
    hosts: "{{ groups['zookeeper-nodes'][0] }}"
    name: '/cdap'
    recursive: yes
    state: absent
  when: cdap_check.rc == 1

- name: Install cdap packages
  apt:
    name: '{{ item }}'
    update_cache: yes
    state: present
  with_items:
    - cdap-gateway
    - cdap-kafka
    - cdap-master
    - cdap-security
    - cdap-ui

- name: Remove cdap-conf link
  file:
     path: '/etc/cdap/conf'
     state: absent

#### Temporary Hack to workaround CDAP-4089
- name: Remove cdap-kafka-log4j jar
  file:
     path: '/opt/cdap/kafka/lib/log4j.log4j-1.2.14.jar'
     state: absent

- name: Create cdap config directory
  file:
     path: '/etc/cdap/conf'
     state: directory
     owner: root
     group: root

- name: Generate cdap configuration
  template:
    src: '{{ item }}.j2'
    dest: '/etc/cdap/conf/{{ item }}'
    owner: cdap
    group: cdap
  with_items:
    - cdap-env.sh
    - cdap-site.xml
    - logback.xml
    - logback-container.xml
